name: flutter_quick_video_encoder
description: Encode raw RGB images to mp4 video using hardware h264 encoders. Also supports PCM audio & m4a files.
version: 1.7.1
homepage: https://github.com/chipweinberger/flutter_quick_video_encoder

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_quick_video_encoder
        pluginClass: FlutterQuickVideoEncoderPlugin
      ios:
        pluginClass: FlutterQuickVideoEncoderPlugin
      macos:
        pluginClass: FlutterQuickVideoEncoderPlugin

